name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: Vrush2004/podcast-generator@main
